#!/bin/bash

rm -rf ./../output_csv_files/
mkdir ./../output_csv_files/
for sim in $( ls ./../Compiled_Simulators/ ); do
  printf "\n### test Simulator named %s ###\n" ${sim}
  chmod u+x ./../Compiled_Simulators/${sim}
  ./bin/mips_testbench ./../Compiled_Simulators/${sim} > ./../output_csv_files/${sim}.csv
  grep 'Fail' ./../output_csv_files/${sim}.csv
done
