#!/bin/sh
#
#



cat bin/case.csv | while IFS=, read -r fileName instr expReturn inchar expOutChar; do

	state=Pass
	message1="x"

	#convert cin from hex to ascii, run the test binary, get output
	cout=$(echo $inchar | xxd -r | $1 ins.bin 2> echo)

	#check error
	if [ "$?" -ne "$expReturn" ]; then
		message1="$message1. Expect return $expReturn, get $?"
		state=Fail
	fi

	if  [ "$?" -ne "$expOutChar" ]; then
	# if [ $? -ne $expReturn ]; then
		message1="${message1}. Expect cout $expReturn, get $cout"
		state=Fail
	fi

	echo "$fileName, $instr, $state, team OOP, $($message1 |tr '\n' ' '),"
done
